services:
  - type: web
    name: api
    env: docker
    plan: free
    dockerContext: ./server
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: LOG_LEVEL
        value: debug
      - key: ENVIRONMENT
        sync: false
